# Site settings
title: Annalogical
name: Anna Doubkova
email: doubkova.anna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about programming and other nerdy things. WebSockets, Test driven development, robotics, mathematics, neural networks, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lithinn
github_username:  lithin

# Build settings
markdown: kramdown
